### ISSUE TITLE
Forward security connections are ignored (don't even get tested)

### ISSUE THREAD

**Issue by genodeftest** [OpenSecurityResearch/ciphertest#6]
I wondered why ciphertest didn't display any Diffie-Hellman ciphers. My installed version of GNUtls tells me that it does support them (just run `gnutls-cli -l`).
Comparing the outputs of https://www.ssllabs.com/ssltest/analyze.html?d=github.com with `ciphertest github.com 443` won't show any DH, only some AES- and ARCFOUR- ciphers.

**Comment by pdbogen** [comment]
Howdy, @genodeftest. I'm not sure if this is what you had in mind, but the new release, v0.2.0, properly supports testing for the ECDHE-* family of key exchanges, and associated searching for supported EC curves.

With this support, cipherTest and Qualys now report a similar list of supported ciphers.

If you have another test case where cipherTest is not detecting support for something that you think it should be, please let me know.

**Comment by genodeftest** [comment]
Ok, that was what I expected. Thank you!
